services:
   harveyod-dev:
      build:
         context: .
         target: development
         dockerfile: ./Dockerfile
      volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules
      ports:
         - '3001:3000'
      command: ['pnpm', 'start:dev']
      depends_on:
         - db
         - redis

   db:
      image: postgres
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: khongbiet
         POSTGRES_DB: harveyod
      volumes:
         - db_data:/var/lib/postgresql/data
      ports:
         - '5433:5432'

   redis:
      image: redis:7
      ports:
         - '6379:6379'

volumes:
   db_data:

networks:
   default:
      driver: bridge
